import PaidPdfPreview from "./PaidPdfPreview"
import {useEffect,useState} from 'react'
import {communityRequest} from '../services/community'
import LoadingState from './LoadingState'
import './Monetization.css'

export default function Monetization() {
  const [state,setState]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState(false),[subject,setSubject]=useState('networks')
  useEffect(()=>{let active=true;communityRequest({action:'monetization'}).then(value=>{if(active)setState(value)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[])
  async function toggle(){setBusy(true);setError('');try{setState(await communityRequest({action:'setMonetization',enabled:!state.enabled}))}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <section className="creator-panel"><header><span className="creator-kicker">CREATOR STUDIO</span><h2>Monetization</h2><p>Your knowledge can have value. Build trust before you earn.</p></header>{error && <p role="alert">{error}</p>}{!state && !error && <LoadingState label="Checking creator eligibility" />}{state && <><div className="creator-goals">{[['Average rating',state.ratingCount?`${state.averageRating.toFixed(2)} / 5`:'No ratings yet','More than 3 / 5',state.averageRating>3,Math.min(state.averageRating/3*100,100)],['Public notes',state.notes,'At least 50 notes',state.notes>=50,Math.min(state.notes/50*100,100)],['Likes received',state.likes.toLocaleString(),'At least 5,000 likes',state.likes>=5000,Math.min(state.likes/5000*100,100)]].map(([label,value,target,met,progress])=><article key={label}><span>{label}<b>{met?'✓':'○'}</b></span><strong>{value}</strong><div className="creator-progress" role="progressbar" aria-label={label} aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${progress}%`}}/></div><small>{target}</small></article>)}</div><div className="creator-enable"><div><strong>{state.eligible?'You’re eligible!':'Keep building your study library'}</strong><p>{state.eligible?'Enable creator monetization preferences.':'All three requirements must be met to enable monetization.'}</p></div><button role="switch" aria-checked={state.enabled} disabled={busy||(!state.eligible&&!state.enabled)} onClick={toggle}>{busy?'Saving…':state.enabled?'Enabled':'Enable monetization'}</button></div><small>Server-verified public notes and reader ratings. Sample notes and self-likes do not count. Payments and payouts are not connected yet.</small></>}<div className="creator-demo"><span className="creator-kicker">PAID NOTE · DEMO</span><label className="creator-pdf-picker">Demo PDF<select value={subject} onChange={e=>{setSubject(e.target.value);setPreview(false)}}><option value="networks">MCA Computer Networks</option><option value="software">MCA Software Engineering</option></select></label><h3>{subject==='networks'?'Computer Networks':'Software Engineering'} — Revision pack</h3><p>Preview the first PDF page free. The remaining pages are locked in this demo.</p><button onClick={()=>setPreview(!preview)} aria-expanded={preview}>{preview?'Close preview':'Preview paid PDF'} · ₹29 demo price</button>{preview && <PaidPdfPreview key={subject} subject={subject} />}</div></section>
}
